name = "vless-worker-cdn"
main = "SRC/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "VLESS_CONFIGS"
id = "26ae405edc964320a2b2da512fbb1eb9"
preview_id = "VLESS_CONFIGS"
